name: magazord_http_client
description: HTTP Client
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0 <4.0.0"

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  magazord_common_packages:
    path: ../common_packages
  magazord_logger:
    path: ../logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  magazord_common_packages_for_tests:
    path: ../common_packages_for_tests
  magazord_lint:
    path: ../lint
