name: products_catalog
description: "A catalog of products, just it, I swear"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  cached_network_image: ^3.3.1
  catppuccin_flutter: ^1.0.0
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0
  logger: ^2.0.2+1
  magazord_common_packages:
    path: ./packages/common_packages
  magazord_http_client:
    path: ./packages/http_client
  magazord_key_value_storage:
    path: ./packages/key_value_storage
  magazord_logger:
    path: ./packages/logger
  mmkv: ^1.3.3
  nested: ^1.0.0
  share_plus: ^7.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  magazord_common_packages_for_tests:
    path: ./packages/common_packages_for_tests
  magazord_lint:
    path: ./packages/lint

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/roboto-v30-latin-100.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/roboto/roboto-v30-latin-100italic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/roboto/roboto-v30-latin-300.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/roboto/roboto-v30-latin-300italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/roboto/roboto-v30-latin-regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/roboto/roboto-v30-latin-italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/roboto/roboto-v30-latin-500.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/roboto/roboto-v30-latin-500italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/roboto/roboto-v30-latin-700.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/roboto/roboto-v30-latin-700italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/roboto/roboto-v30-latin-900.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/roboto/roboto-v30-latin-900italic.ttf
          style: italic
          weight: 900
